# Generated by Django 3.2.7 on 2021-10-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='firstname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='lastname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
