# Generated by Django 3.2.7 on 2021-10-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20211006_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='thank_you_text',
        ),
    ]
