# Generated by Django 3.2.7 on 2021-10-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20211006_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='firstname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='lastname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
