# Generated by Django 3.2.7 on 2021-10-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='Firstname',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Lastname',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
